"""initial schema

Revision ID: d501f26fb187
Revises: 
Create Date: 2026-04-01 15:02:36.941541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd501f26fb187'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               comment='Filesystem-safe name used as directory key',
               existing_nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment='Human-readable title from the PDF',
               existing_nullable=True)
    op.alter_column('books', 'grade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('books', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('books', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'English'::text"))
    op.drop_constraint(op.f('books_name_key'), 'books', type_='unique')
    op.drop_index(op.f('idx_books_name'), table_name='books')
    op.create_index(op.f('ix_books_name'), 'books', ['name'], unique=True)
    op.alter_column('chapters', 'ontology_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               comment='e.g. C_1',
               existing_nullable=True)
    op.alter_column('chapters', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_constraint(op.f('chapters_book_id_number_key'), 'chapters', type_='unique')
    op.drop_index(op.f('idx_chapters_book'), table_name='chapters')
    op.create_index(op.f('ix_chapters_book_id'), 'chapters', ['book_id'], unique=False)
    op.create_unique_constraint('uq_chapter_book_number', 'chapters', ['book_id', 'number'])
    op.drop_index(op.f('idx_class_students_student'), table_name='class_students')
    op.alter_column('classes', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('classes', 'grade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('classes', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('classes', 'academic_year',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('idx_classes_teacher'), table_name='classes')
    op.create_index(op.f('ix_classes_teacher_id'), 'classes', ['teacher_id'], unique=False)
    op.alter_column('exercises', 'ontology_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               comment='e.g. E_1_2_1',
               existing_nullable=True)
    op.drop_index(op.f('idx_exercises_topic'), table_name='exercises')
    op.create_index(op.f('ix_exercises_topic_id'), 'exercises', ['topic_id'], unique=False)
    op.alter_column('lesson_plans', 'topic_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('lesson_plans', 'grade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('lesson_plans', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('idx_lesson_plans_teacher'), table_name='lesson_plans')
    op.drop_index(op.f('idx_lesson_plans_topic'), table_name='lesson_plans')
    op.create_index(op.f('ix_lesson_plans_teacher_id'), 'lesson_plans', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_topic_id'), 'lesson_plans', ['topic_id'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='e.g. taught_today, reminder',
               existing_nullable=False)
    op.alter_column('notifications', 'topic_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('idx_notifications_student'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_student_unread'), table_name='notifications', postgresql_where='(NOT is_read)')
    op.create_index(op.f('ix_notifications_student_id'), 'notifications', ['student_id'], unique=False)
    op.alter_column('quiz_submissions', 'topic_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('quiz_submissions', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0.0 – 1.0',
               existing_nullable=False)
    op.drop_index(op.f('idx_quiz_student'), table_name='quiz_submissions')
    op.drop_index(op.f('idx_quiz_topic'), table_name='quiz_submissions')
    op.create_index(op.f('ix_quiz_submissions_student_id'), 'quiz_submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_quiz_submissions_topic_id'), 'quiz_submissions', ['topic_id'], unique=False)
    op.alter_column('sidebars', 'ontology_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               comment='e.g. S_1_2_1',
               existing_nullable=True)
    op.drop_index(op.f('idx_sidebars_topic'), table_name='sidebars')
    op.create_index(op.f('ix_sidebars_topic_id'), 'sidebars', ['topic_id'], unique=False)
    op.drop_index(op.f('idx_mastery_student'), table_name='student_topic_mastery')
    op.drop_index(op.f('idx_mastery_topic'), table_name='student_topic_mastery')
    op.alter_column('students', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('students', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('students', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('students', 'learning_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               comment='beginner | intermediate | advanced',
               existing_nullable=False,
               existing_server_default=sa.text("'intermediate'::text"))
    op.alter_column('students', 'learning_style',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               comment='visual | story | examples | auditory',
               existing_nullable=False,
               existing_server_default=sa.text("'visual'::text"))
    op.alter_column('students', 'attention_span',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               comment='short | medium | long',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::text"))
    op.alter_column('students', 'language_proficiency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'native'::text"))
    op.drop_constraint(op.f('students_email_key'), 'students', type_='unique')
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.alter_column('study_plans', 'topic_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('study_plans', 'grade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('study_plans', 'context_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='e.g. post-lecture-review',
               existing_nullable=True)
    op.drop_index(op.f('idx_study_plans_student'), table_name='study_plans')
    op.create_index(op.f('ix_study_plans_student_id'), 'study_plans', ['student_id'], unique=False)
    op.create_index(op.f('ix_study_plans_topic_id'), 'study_plans', ['topic_id'], unique=False)
    op.drop_index(op.f('idx_taught_topics_teacher'), table_name='taught_topics')
    op.drop_index(op.f('idx_taught_topics_topic'), table_name='taught_topics')
    op.create_index(op.f('ix_taught_topics_class_id'), 'taught_topics', ['class_id'], unique=False)
    op.create_index(op.f('ix_taught_topics_teacher_id'), 'taught_topics', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_taught_topics_topic_id'), 'taught_topics', ['topic_id'], unique=False)
    op.alter_column('teachers', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('teachers', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('teachers', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('teachers', 'teaching_style',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='lecture | activity | storytelling',
               existing_nullable=False,
               existing_server_default=sa.text("'activity'::text"))
    op.alter_column('teachers', 'lesson_duration',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'45 minutes'::text"))
    op.alter_column('teachers', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'English'::text"))
    op.alter_column('teachers', 'activity_preference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='games | puzzles | worksheets',
               existing_nullable=False,
               existing_server_default=sa.text("'worksheets'::text"))
    op.alter_column('teachers', 'assessment_style',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='quizzes | exercises',
               existing_nullable=False,
               existing_server_default=sa.text("'quizzes'::text"))
    op.alter_column('teachers', 'difficulty_preference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               comment='easier | medium | harder',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::text"))
    op.drop_constraint(op.f('teachers_email_key'), 'teachers', type_='unique')
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.alter_column('topics', 'ontology_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               comment='e.g. T_1_2',
               existing_nullable=True)
    op.alter_column('topics', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('topics', 'position',
               existing_type=sa.INTEGER(),
               comment='Order within the chapter',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('topics', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               comment='untaught | partial | taught',
               existing_nullable=False,
               existing_server_default=sa.text("'untaught'::text"))
    op.drop_index(op.f('idx_topics_chapter'), table_name='topics')
    op.drop_constraint(op.f('topics_chapter_id_position_key'), 'topics', type_='unique')
    op.create_index(op.f('ix_topics_chapter_id'), 'topics', ['chapter_id'], unique=False)
    op.create_unique_constraint('uq_topic_chapter_position', 'topics', ['chapter_id', 'position'])
    op.alter_column('worksheets', 'topic_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('worksheets', 'grade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('worksheets', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('worksheets', 'difficulty',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               comment='easy | medium | hard | mixed',
               existing_nullable=True)
    op.alter_column('worksheets', 'worksheet_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               comment='practice | assessment | homework',
               existing_nullable=True)
    op.drop_index(op.f('idx_worksheets_lesson_plan'), table_name='worksheets')
    op.create_index(op.f('ix_worksheets_lesson_plan_id'), 'worksheets', ['lesson_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worksheets_lesson_plan_id'), table_name='worksheets')
    op.create_index(op.f('idx_worksheets_lesson_plan'), 'worksheets', ['lesson_plan_id'], unique=False)
    op.alter_column('worksheets', 'worksheet_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='practice | assessment | homework',
               existing_nullable=True)
    op.alter_column('worksheets', 'difficulty',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='easy | medium | hard | mixed',
               existing_nullable=True)
    op.alter_column('worksheets', 'subject',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('worksheets', 'grade',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('worksheets', 'topic_name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_topic_chapter_position', 'topics', type_='unique')
    op.drop_index(op.f('ix_topics_chapter_id'), table_name='topics')
    op.create_unique_constraint(op.f('topics_chapter_id_position_key'), 'topics', ['chapter_id', 'position'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_topics_chapter'), 'topics', ['chapter_id'], unique=False)
    op.alter_column('topics', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='untaught | partial | taught',
               existing_nullable=False,
               existing_server_default=sa.text("'untaught'::text"))
    op.alter_column('topics', 'position',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Order within the chapter',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('topics', 'name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('topics', 'ontology_id',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='e.g. T_1_2',
               existing_nullable=True)
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.create_unique_constraint(op.f('teachers_email_key'), 'teachers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('teachers', 'difficulty_preference',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='easier | medium | harder',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::text"))
    op.alter_column('teachers', 'assessment_style',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='quizzes | exercises',
               existing_nullable=False,
               existing_server_default=sa.text("'quizzes'::text"))
    op.alter_column('teachers', 'activity_preference',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='games | puzzles | worksheets',
               existing_nullable=False,
               existing_server_default=sa.text("'worksheets'::text"))
    op.alter_column('teachers', 'language',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'English'::text"))
    op.alter_column('teachers', 'lesson_duration',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'45 minutes'::text"))
    op.alter_column('teachers', 'teaching_style',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='lecture | activity | storytelling',
               existing_nullable=False,
               existing_server_default=sa.text("'activity'::text"))
    op.alter_column('teachers', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('teachers', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('teachers', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_taught_topics_topic_id'), table_name='taught_topics')
    op.drop_index(op.f('ix_taught_topics_teacher_id'), table_name='taught_topics')
    op.drop_index(op.f('ix_taught_topics_class_id'), table_name='taught_topics')
    op.create_index(op.f('idx_taught_topics_topic'), 'taught_topics', ['topic_id'], unique=False)
    op.create_index(op.f('idx_taught_topics_teacher'), 'taught_topics', ['teacher_id'], unique=False)
    op.drop_index(op.f('ix_study_plans_topic_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_student_id'), table_name='study_plans')
    op.create_index(op.f('idx_study_plans_student'), 'study_plans', ['student_id'], unique=False)
    op.alter_column('study_plans', 'context_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='e.g. post-lecture-review',
               existing_nullable=True)
    op.alter_column('study_plans', 'grade',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('study_plans', 'topic_name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.create_unique_constraint(op.f('students_email_key'), 'students', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('students', 'language_proficiency',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'native'::text"))
    op.alter_column('students', 'attention_span',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='short | medium | long',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::text"))
    op.alter_column('students', 'learning_style',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='visual | story | examples | auditory',
               existing_nullable=False,
               existing_server_default=sa.text("'visual'::text"))
    op.alter_column('students', 'learning_level',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='beginner | intermediate | advanced',
               existing_nullable=False,
               existing_server_default=sa.text("'intermediate'::text"))
    op.alter_column('students', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('students', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('students', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_mastery_topic'), 'student_topic_mastery', ['topic_id'], unique=False)
    op.create_index(op.f('idx_mastery_student'), 'student_topic_mastery', ['student_id'], unique=False)
    op.drop_index(op.f('ix_sidebars_topic_id'), table_name='sidebars')
    op.create_index(op.f('idx_sidebars_topic'), 'sidebars', ['topic_id'], unique=False)
    op.alter_column('sidebars', 'ontology_id',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='e.g. S_1_2_1',
               existing_nullable=True)
    op.drop_index(op.f('ix_quiz_submissions_topic_id'), table_name='quiz_submissions')
    op.drop_index(op.f('ix_quiz_submissions_student_id'), table_name='quiz_submissions')
    op.create_index(op.f('idx_quiz_topic'), 'quiz_submissions', ['topic_id'], unique=False)
    op.create_index(op.f('idx_quiz_student'), 'quiz_submissions', ['student_id'], unique=False)
    op.alter_column('quiz_submissions', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0.0 – 1.0',
               existing_nullable=False)
    op.alter_column('quiz_submissions', 'topic_name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_student_id'), table_name='notifications')
    op.create_index(op.f('idx_notifications_student_unread'), 'notifications', ['student_id'], unique=False, postgresql_where='(NOT is_read)')
    op.create_index(op.f('idx_notifications_student'), 'notifications', ['student_id'], unique=False)
    op.alter_column('notifications', 'topic_name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='e.g. taught_today, reminder',
               existing_nullable=False)
    op.drop_index(op.f('ix_lesson_plans_topic_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_teacher_id'), table_name='lesson_plans')
    op.create_index(op.f('idx_lesson_plans_topic'), 'lesson_plans', ['topic_id'], unique=False)
    op.create_index(op.f('idx_lesson_plans_teacher'), 'lesson_plans', ['teacher_id'], unique=False)
    op.alter_column('lesson_plans', 'subject',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('lesson_plans', 'grade',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('lesson_plans', 'topic_name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_exercises_topic_id'), table_name='exercises')
    op.create_index(op.f('idx_exercises_topic'), 'exercises', ['topic_id'], unique=False)
    op.alter_column('exercises', 'ontology_id',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='e.g. E_1_2_1',
               existing_nullable=True)
    op.drop_index(op.f('ix_classes_teacher_id'), table_name='classes')
    op.create_index(op.f('idx_classes_teacher'), 'classes', ['teacher_id'], unique=False)
    op.alter_column('classes', 'academic_year',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('classes', 'subject',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('classes', 'grade',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('classes', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_class_students_student'), 'class_students', ['student_id'], unique=False)
    op.drop_constraint('uq_chapter_book_number', 'chapters', type_='unique')
    op.drop_index(op.f('ix_chapters_book_id'), table_name='chapters')
    op.create_index(op.f('idx_chapters_book'), 'chapters', ['book_id'], unique=False)
    op.create_unique_constraint(op.f('chapters_book_id_number_key'), 'chapters', ['book_id', 'number'], postgresql_nulls_not_distinct=False)
    op.alter_column('chapters', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chapters', 'ontology_id',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='e.g. C_1',
               existing_nullable=True)
    op.drop_index(op.f('ix_books_name'), table_name='books')
    op.create_index(op.f('idx_books_name'), 'books', ['name'], unique=False)
    op.create_unique_constraint(op.f('books_name_key'), 'books', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('books', 'language',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'English'::text"))
    op.alter_column('books', 'subject',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('books', 'grade',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('books', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='Human-readable title from the PDF',
               existing_nullable=True)
    op.alter_column('books', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='Filesystem-safe name used as directory key',
               existing_nullable=False)
    # ### end Alembic commands ###
